# Site wide configuration

title:            r.checagarcia
locale:           en_US
url:              http://rchg.github.io


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll/scholar

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

scholar:
  style: apa
  locale: en

  sort_by: none
  order: ascending

  source: ./_bibliography

  bibliography: references.bib
  bibliography_template: "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"
  
    
# Site owner
owner:
  name: R.Checa-Garcia
  avatar: rainy-dragon.jpeg
  bio: "Atmospheric Physics Scientist"
  email:
  job: www.imk-asf.kit.edu/english/
  disqus-shortname: 
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: rchg
  sourceforge: rchecagarcia/profile/
  bitbucket: rchecagarcia
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["_vendor","lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
